version: '3'

services:
  app:
    image: nginx:latest
    restart: always
    networks:
      - treafik-network
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.ghart.space`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.routers.app.tls.certresolver=leresolver"
      - "traefik.docker.network=treafik-network"

networks:
  treafik-network:
    external: true
    name: treafik-network
